# Generated by Django 2.2.14 on 2020-11-30 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesores', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('estudiante', models.ManyToManyField(null=True, related_name='estudiante', to='estudiantes.Estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.Profesor')),
            ],
        ),
    ]
