# Generated by Django 2.2.14 on 2020-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='estudiante',
            field=models.ManyToManyField(related_name='estudiante', to='estudiantes.Estudiante'),
        ),
    ]
