# Generated by Django 2.2.14 on 2020-11-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=8)),
                ('edad', models.IntegerField(null=True)),
                ('activo', models.BooleanField(null=True)),
                ('f_nacimiento', models.DateField(null=True)),
            ],
        ),
    ]
